### ISSUE TITLE
Port pam.js to use eea.searchserver.js and Docker

### ISSUE THREAD

**Issue by mihaibivol** [eea/eea.docker.pam#1]
The first step is to move [this directory]() into this repo:
- [ ] Create a dir called `app`
- [ ] Move all the pam code in app and rename `pam.js` to `app.js`
- [ ] Change package.json to use the latest `express` and add `eea.searchserver.js` as a dependency ([model](https://github.com/eea/eea.docker.eeasearch/blob/master/app/package.json))
- [ ] Make sure you don't leave things that will not be used anymore e.g. you won't need node-crontab for pam.

After updating express to the latest version some of the middleware won't be included
Also, we need to use eea.searchserver.js

Adapt app.js (former pam.js)
- [ ] Basically copy [this](https://github.com/eea/eea.docker.eeasearch/blob/master/app/app.js)
  over app.js and remove the sync and crontab logic.
- [ ] Comment out the managementCommands part and  replace with this line `app.set('managementCommands', {});` This will enable testing without management commands
- [ ] Add the other routes to your app
- [ ] Ask @mihaibivol what are the new middleware functions.
- [ ] The new app.js will use a singe `settings.json` file for both production and development.
  Use [this as a model](https://github.com/eea/eea.docker.eeasearch/blob/master/app/settings.json)
- [ ] Replace the local path for external templates with a path you have rights to write (e.g. /tmp/ext_templates) You will revert to `/external_templates` after making sure the app actually runs locally.
- [ ] Set the index and type correctly
- [ ] For the first step add in the `elastic` field these. They will enable you to test the /api endpoint with already indexed data
  - elastic_host: centaurus-dev.eea.europa.eu
  - elastic_port: 80
  - elastic_path: /elasticsearch/

Now the app will automatically invalidate templates at the first request after being started.
(by using the templates_required middleware)
You can now test that the api is running by:

``` bash
npm install
node app.js runserver
curl http://localhost:3000/api/
```

Yo will see that going in your browser to http://localhost:3000 won't work because the tempalte
is not rendered correctly. This happens  because:
- You are using the base_path that was set in nconf which isn't needed anymore
- You can't include a dynamic template
- [ ] Perform this hack to be able to render the templates from variables
  - https://github.com/eea/eea.docker.eeasearch/blob/master/app/routes/index.js
  - use the (templateRender)[https://github.com/eea/eea.docker.eeasearch/blob/master/app/views/index.jade#L30] function in the jade template 
  - [ ] Instruct the pam app to use calls to ./api instead of calling the elasticsearch endpoint you configured directly from the client
  - For jquery.facetview.js in the init code you have to add this (https://github.com/eea/eea.docker.eeasearch/blob/master/app/public/js/search.js#L238): 
  - Calls from the server can be made directly to the configured elastic even if it's not advised :)

**Comment by alecghica** [comment]
+1 :)
